//Prime+Probe
#define ES_EVICTION_COUNTER 8
#define ES_NUMBER_OF_ACCESSES_IN_LOOP 5
#define ES_DIFFERENT_ADDRESSES_IN_LOOP 1

//Evict+Reload
//#define ES_EVICTION_COUNTER 12
//#define ES_NUMBER_OF_ACCESSES_IN_LOOP 1
//#define ES_DIFFERENT_ADDRESSES_IN_LOOP 1
